name: Run Backend

on:
  workflow_dispatch:

jobs:
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Run backend
        run: npm run run
        
